# Generated by Django 5.2.7 on 2025-10-28 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('marc_tag', models.TextField(blank=True, null=True)),
                ('dublin_core', models.TextField(blank=True, null=True)),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True)),
                ('issn', models.CharField(blank=True, max_length=30, null=True)),
                ('lccn', models.CharField(blank=True, max_length=30, null=True)),
                ('dewey_decimal', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('contributors', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of copies available')),
                ('can_be_borrowed', models.BooleanField(default=True, help_text='Can this catalog item be borrowed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_manage_catalog', 'Can manage all catalog records')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('student_category', models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('masters', 'Masters'), ('phd', 'PhD'), ('none', 'None')], max_length=50, null=True)),
                ('staff_category', models.CharField(blank=True, choices=[('librarian', 'Librarian'), ('member', 'Memeber'), ('staff', 'Staff'), ('donator', 'Donator'), ('none', 'None')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('donation', 'Donation'), ('exchange', 'Exchange')], max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_acquired', models.DateField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_acquisition', 'Can manage all acquisition records')],
            },
        ),
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_data', models.TextField()),
                ('reg_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(choices=[('thumbprint', 'Thumbprint'), ('manual', 'Manual'), ('id_card', 'ID Card')], default='manual', max_length=20)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_attendance', 'Can manage all attendance records')],
            },
        ),
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, help_text='Student name', max_length=255, null=True)),
                ('student_card_id', models.CharField(blank=True, help_text='Student card ID', max_length=255, null=True)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('reserve', 'Reserve')], default='borrowed', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulations', to='main.catalog')),
            ],
            options={
                'permissions': [('can_manage_circulation', 'Can manage all circulation records')],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_duty', 'Can manage all duty records')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_messages', 'Can manage all messages')],
            },
        ),
    ]
