# Generated by Django 5.2.7 on 2025-11-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulation',
            name='student_card_id',
        ),
    ]
