# Generated by Django 5.2.6 on 2025-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_owner_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('subscribed', 'Subscribed Database'), ('open_access', 'Open Access Database'), ('ebooks', 'E-Books Website'), ('journals', 'Research Journals Websites')], max_length=50),
        ),
    ]
