# Generated by Django 5.2.7 on 2025-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_circulation_student_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text='User role (admin, staff, student, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circulation',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
