# Generated by Django 5.2.7 on 2025-11-22 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_role_alter_circulation_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(default='barcode', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_attendance', 'Can manage all attendance records')],
            },
        ),
        migrations.DeleteModel(
            name='Attendace',
        ),
    ]
