# Generated by Django 5.2.6 on 2025-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_department_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('anatomy', 'Anatomy'), ('nutrition', 'Human Nutrition & Dietetics'), ('lab_science', 'Medical Laboratory Science'), ('nursing', 'Nursing Science'), ('optometry', 'Optometry'), ('pharmacology', 'Pharmacology'), ('physiology', 'Physiology'), ('physiotherapy', 'Physiotherapy'), ('general_studies', 'General Studies'), ('radiography', 'Radiography and Radiation Science'), ('electronic_db', 'Electronic Database'), ('library_catalog', 'Library Catalog'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('medical_journals', 'Medical Journals')], max_length=50)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='ebook/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ebook/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_create_ebook', 'Can create ebook')],
            },
        ),
        migrations.CreateModel(
            name='EJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('anatomy', 'Anatomy'), ('nutrition', 'Human Nutrition & Dietetics'), ('lab_science', 'Medical Laboratory Science'), ('nursing', 'Nursing Science'), ('optometry', 'Optometry'), ('pharmacology', 'Pharmacology'), ('physiology', 'Physiology'), ('physiotherapy', 'Physiotherapy'), ('general_studies', 'General Studies'), ('radiography', 'Radiography and Radiation Science'), ('electronic_db', 'Electronic Database'), ('library_catalog', 'Library Catalog'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('medical_journals', 'Medical Journals')], max_length=50)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='ejournal/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ejournal/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_create_ebook', 'Can create ebook')],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='resources/thumbnails/')),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('subscribed_db', 'Subscribed Database'), ('open_access_db', 'Open Access Database'), ('ebooks', 'E-books Website'), ('journals', 'Research Journals Websites'), ('thesis', 'Thesis and Dissertation'), ('gov_pub', 'Government Publication'), ('plagiarism', 'Plagiarism Checker'), ('paraphrasing', 'Paraphrasing Tools'), ('citation', 'Citation Tools'), ('grants', 'Grants')], default='journals', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
