# Generated by Django 5.2.7 on 2025-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_catalog_author_catalog_barcode_user_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_category',
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('alumnus', 'Alumnus'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
