# Generated by Django 5.2.6 on 2025-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ebook_ejournal_resource_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejournal',
            name='upload_file',
        ),
        migrations.AlterField(
            model_name='ebook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/ebook/images/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/ebook/files/'),
        ),
        migrations.AlterField(
            model_name='ejournal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/ejournal/images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/resources/thumbnails/'),
        ),
    ]
