# Generated by Django 5.2.7 on 2025-11-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_student_category_user_user_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='student_name',
            new_name='borrower_name',
        ),
    ]
