# Generated by Django 5.2.6 on 2025-09-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ejournal_upload_file_alter_ebook_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejournal',
            name='approved',
        ),
    ]
