# Generated by Django 5.2.6 on 2025-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ejournal_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='newpaper/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ejournal',
            options={},
        ),
        migrations.AlterField(
            model_name='ebook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ebook/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='ebook/files/'),
        ),
        migrations.AlterField(
            model_name='ejournal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ejournal/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(upload_to='resources/thumbnails/'),
        ),
    ]
