# Generated by Django 5.2.7 on 2025-11-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_student_name_circulation_borrower_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulation',
            name='borrower_name',
        ),
        migrations.AddField(
            model_name='circulation',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
