# Generated by Django 5.2.7 on 2025-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_circulation_borrower_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sign_type',
            field=models.CharField(choices=[('signin', 'Sign In'), ('signout', 'Sign Out'), ('other', 'Other')], default='signout', max_length=20),
        ),
    ]
