# Generated by Django 5.2.6 on 2025-09-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_newspaper_alter_ejournal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
