# Generated by Django 5.2.6 on 2025-09-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newspaper_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_category',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='newspaper/thumbnails/'),
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255, unique=True)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('student_category', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
