# Generated by Django 5.2.6 on 2025-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_department_user_faculty_user_student_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejournal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ejournal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
