# Generated by Django 5.2.6 on 2025-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_subject_ejournal_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
