# Generated by Django 5.2.6 on 2025-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_idcard_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejournal',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
