# Generated by Django 5.2.7 on 2025-10-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_id', models.CharField(max_length=100, unique=True)),
                ('fingerprint_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='ejournal',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='LibraryDetails',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='BorrowBook',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='EBook',
        ),
        migrations.DeleteModel(
            name='EJournal',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='IDCard',
        ),
    ]
