# Generated by Django 5.2.7 on 2025-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_fingerprint_remove_borrowbook_user_delete_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
