# Generated by Django 5.2.7 on 2025-10-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fingerprint_category_fingerprint_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='fp_id',
        ),
    ]
