# Generated by Django 5.2.7 on 2025-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_fingerprint_fp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
