# Generated by Django 5.2.7 on 2025-10-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_fingerprint_items_fingerprint_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='user',
        ),
    ]
