# Generated by Django 5.2.7 on 2025-10-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_acquisition_attendace_catalog_circulation_duty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisition',
            options={'permissions': [('can_manage_acquisition', 'Can manage all acquisition records')]},
        ),
        migrations.AlterModelOptions(
            name='attendace',
            options={'permissions': [('can_manage_attendance', 'Can manage all attendance records')]},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'permissions': [('can_manage_catalog', 'Can manage all catalog records')]},
        ),
        migrations.AlterModelOptions(
            name='circulation',
            options={'permissions': [('can_manage_circulation', 'Can manage all circulation records')]},
        ),
        migrations.AlterModelOptions(
            name='duty',
            options={'permissions': [('can_manage_duty', 'Can manage all duty records')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_manage_messages', 'Can manage all messages')]},
        ),
    ]
