# Generated by Django 5.2.7 on 2025-10-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_acquisition_options_alter_attendace_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendace',
            name='fp_id',
        ),
    ]
