# Generated by Django 5.2.7 on 2025-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_attendace_fp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
