# Generated by Django 5.2.7 on 2025-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_catalog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='can_be_borrowed',
            field=models.BooleanField(default=True, help_text='Can this catalog item be borrowed?'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of copies available'),
        ),
    ]
