# Generated by Django 5.2.7 on 2025-10-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_catalog_can_be_borrowed_catalog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='student_card_id',
            field=models.CharField(blank=True, help_text='Student card ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='circulation',
            name='student_name',
            field=models.CharField(blank=True, help_text='Student name', max_length=255, null=True),
        ),
    ]
