# Generated by Django 5.2.7 on 2025-10-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_circulation_student_card_id_circulation_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulation',
            name='user',
        ),
    ]
