# Generated by Django 5.2.7 on 2025-10-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_circulation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
